baseURL = "http://localhost"
copyright = "FriedFireAnt"
defaultContentLanguage = "en-au"
disableKinds = ["taxonomy", "taxonomyTerm"]
languageCode = "en-au"
paginate = 5
summaryLength = 7
title = "FriedFireAnt"
[languages.en-au]
weight = 1
[markup.goldmark.renderer]
unsafe = true
