baseURL = "http://localhost"
disableKinds = [ "taxonomy", "taxonomyTerm" ]
languageCode = "en-au"
defaultContentLanguage = "en-au"
title = "FriedFireAnt"
copyright = "FriedFireAnt"
paginate = 5
summaryLength = 7

[languages.en-au]
weight = 1

[markup.goldmark.renderer]
unsafe = true

# menu links via config file
# menu:
#   main:
#   - identifier: "about"
#     name: "About Me"
#     url: "/about"
#     weight: 21
#   - name: Google
#     url: http://www.google.com/
#     weight: 100
#     params:
#       blank: true